# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# https://www.appveyor.com/ Windows CI configuration file.

environment:
  matrix:
    # Toolkit supports Python 2.6 and 2.7, so build for both of these versions of Python.
    - PYTHON: "C:\\Python26"
    # Do not attempt to run code coverage with Python 2.6, as this version of Python can't pip install
    # modules anymore.
      RUN_COVERAGE: "0"
    - PYTHON: "C:\\Python27"
      RUN_COVERAGE: "1"

  # To update these values, visit AppVeyor's site, click the user icon and scroll down to Encrypt Data.
  SHOTGUN_HOST:
    secure: 1klEyyzGkwq7KyTgI+9nqiqCNcdOXLVR/P8nXGgKu2kLke3ui81KhoAkckJqa9da
  SHOTGUN_SCRIPT_NAME:
    secure: snTNqoprEkQTVQD3cK9mpQ==
  SHOTGUN_SCRIPT_KEY:
    secure: 59Vs3pq1DhG2V7z4hGKNMAmiKC41wW8dnfw4fe47KTHWTSmXbgsjPW4vPyeO2JRUxKEseQOBn+7jVdeb7XWIE9LgP9n34/lWTyblJGvfqyM=

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Do not pip install requirements if we're not running code coverage.
  - "IF /I \"%RUN_COVERAGE%\" EQU \"1\" %CMD_IN_ENV% pip install -r tests\\ci_requirements.txt"

test_script:
  - "tests\\run_appveyor.bat"

after_test:
  - "IF /I \"%RUN_COVERAGE%\" EQU \"1\" codecov"
